# Generated by Django 3.1.6 on 2022-07-07 02:03

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BuyerInformation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('BName_M', models.CharField(max_length=50, null=True)),
                ('BAddress_M', models.CharField(max_length=50, null=True)),
                ('BContact_M', models.PositiveIntegerField(blank=True, default=0, null=True, validators=[django.core.validators.MaxValueValidator(99999999999), django.core.validators.MinValueValidator(0)])),
                ('BEmail_M', models.EmailField(blank=True, default='', max_length=254, null=True)),
                ('BCompanyName_M', models.CharField(max_length=30, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ClientInformation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CName_M', models.CharField(max_length=50, null=True)),
                ('CAddress_M', models.CharField(max_length=50, null=True)),
                ('CContact_M', models.PositiveIntegerField(blank=True, default=0, null=True, validators=[django.core.validators.MaxValueValidator(99999999999), django.core.validators.MinValueValidator(0)])),
                ('CEmail_M', models.EmailField(blank=True, default='', max_length=254, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ItemName_M', models.CharField(max_length=200, null=True)),
                ('ItemDesc_M', models.CharField(max_length=20, null=True)),
                ('Quantity_M', models.CharField(max_length=200, null=True)),
                ('Unit_M', models.CharField(max_length=200, null=True)),
                ('Price_M', models.CharField(max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='PaymentMethod',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='RecycableMaterialsReport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('RMDate_M', models.DateField(blank=True, null=True)),
                ('RMPickupDate_M', models.DateField(blank=True, null=True)),
                ('RMBNo_id_M', models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='recycle.buyerinformation')),
                ('RMCNo_id_M', models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='recycle.clientinformation')),
                ('RMItemCode_id_M', models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='recycle.item')),
            ],
        ),
        migrations.CreateModel(
            name='PaymentInformation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('PI_AcctName_M', models.CharField(max_length=50, null=True)),
                ('PI_AcctNo_M', models.CharField(max_length=50, null=True)),
                ('PI_ItemCode_M', models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='recycle.item')),
                ('PI_PM_id_M', models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='recycle.paymentmethod')),
            ],
        ),
        migrations.CreateModel(
            name='FeedbackReport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('FBR_Rating_M', models.CharField(choices=[('Very Satisfied', 5), ('Satisfied', 4), ('Neutral', 3), ('Disssatisfied', 2), ('Very Disssatisfied', 1)], max_length=100)),
                ('FBR_Desc_M', models.CharField(max_length=50, null=True)),
                ('FBR_Comments_M', models.CharField(max_length=1000, null=True)),
                ('FBR_BNo_M', models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='recycle.buyerinformation')),
                ('FBR_CNo_M', models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='recycle.clientinformation')),
            ],
        ),
    ]
